### ISSUE TITLE
decide future of current RGB21 implementation

### ISSUE THREAD

**Issue by zoedberg** [LNP-BP/LNPBPs#159]
From https://github.com/RGB-WG/rgb-schemata/pull/3 I understood that currently we can support only one non-fractionable NFT.
But in [LNPBP 21](https://github.com/LNP-BP/LNPBPs/blob/master/lnpbp-0021.md) it's still documented that multiple [tokens](https://github.com/LNP-BP/LNPBPs/blob/master/lnpbp-0021.md?plain=1#L120) and [assetOwner](https://github.com/LNP-BP/LNPBPs/blob/master/lnpbp-0021.md?plain=1#L130) could be present.
So I'm wondering if the current interface, which is not strictly implementing LNPBP 21, is final or not.
IMO if the intention is to use this interface in mainnet we should write a dedicated LNPBP for it.

**Comment by dr-orlovsky** [comment]
An interface defines API and what is possible. Schemata provides implementation under the rules of the interface. Multiple schemata (and multiple implementations) of the same interface can exist.

RGB21 is the interface standard. It defines that NFT can have multiple tokens - but does not require the presence of a collection and not a single token. It also allows fractional tokens - but does not require each NFT to be fractional.

So there is nothing to decide: if somebody needs fractional NFT he needs to write a corresponding contract (i.e. schema) providing fractionality and implement RGB21 - no changes to RGB21 are needed. Also, nothing is required to be changed in the existing schema and its implementation, since it is the schema for singular non-fractionable NFTs, which is also needed for some cases.

Finally, this issue is nohow related to the standards. For the implementing fractional NFTs or collections a pull request to the `rgb-schemata` - or a separate independent repository has to be created (or an issue there to do that one day).
