### ISSUE TITLE
RGB: Use i64 instead of i32 for Timestamps in interface standards

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/LNPBPs#165]
Otherwise contracts can't be created after 2038

RGB standard library has also to be updated

CC @fedsten @zoedberg @nicbus @cryptoquick @crisdut

**Comment by cryptoquick** [comment]
Sure, this is fine so long as it doesn't break consensus. If it does, it'd be really helpful to know, we're about to release our latest today. Also, maybe you could use a GitHub tag for that, so I don't have to ask always :)

**Comment by dr-orlovsky** [comment]
It may create complications since if you release assets before this change we would need to maintain two versions of RGB20/21 interface (name them differently etc).

I propose to release the i64 fix today such that you can use it to do latest assets without the need to maintain legacy format.

PS for sure I'll do label

**Comment by dr-orlovsky** [comment]
Btw whatever we do in this repo can't have any consensus effects. Consensus-breaking changes may happen knly in consensus repos (`rgb-core, bp-core, aluvm, strict-types/encoding, client_side_validation`)

**Comment by cryptoquick** [comment]
I see, that makes sense. It also gets increasingly difficult to maintain older versions of Rust libraries as things get outdated, say through security patches, so that situation is best avoided. Please let us know as soon as you have something we can use.

Perhaps a better label might be `major-change`, then, as a major indicates a breaking change, even if it doesn't necessarily break consensus.

**Comment by fedsten** [comment]
ACK

**Comment by crisdut** [comment]
ACK

**Comment by dr-orlovsky** [comment]
Closed with #90
