### ISSUE TITLE
LNPBP-2: embeding LNPBP-1 commitments into transaction outputs

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/LNPBPs#4]
Discussing https://github.com/LNP-BP/lnpbps/blob/master/lnpbp-0002.md

**Comment by inaltoasinistra** [comment]
> 3. Each of the n topmost 33-byte-long stack elements before an execution of Bitcoin script matching the pattern OP_PUSH <n> OP_CHECKMULTISIG[VERIFY]

Why cannot we use only the first pubkey?

> With partial commitments, having some of the public keys tweaked with the message digest, and some left intact, it will be impossible to define a simple and deterministic commitment scheme for an arbitrary script and output type that will prevent any potential double-commitments.

We cannot use arbitrary scripts anyway, because we must identify where pubkeys are.
If I understood, the scripts templates in section ["Deterministic definition for a cryptographically-committable public key fingerprint within transaction output"](https://github.com/LNP-BP/lnpbps/blob/master/lnpbp-0002.md#deterministic-definition-for-a-cryptographically-committable-public-key-fingerprint-within-transaction-output) are needed to find wehere pubkeys are.

I don't understand what are "partial commitments"

**Comment by dr-orlovsky** [comment]
Peter Wuille has just confirmed that it will work (in Taproot IRC chat), so I will add @inaltoasinistra proposal to the specs

**Comment by dr-orlovsky** [comment]
> Why cannot we use only the first pubkey?

Because public key tweaking will change the order of the pub keys if they are deterministically ordered according, like with BIP67
