### ISSUE TITLE
Asset names in RGB Schema

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/LNPBPs#60]
Seems we need four type of asset name:
- Main unit of accounting (like "Bitcoin")
- Ticker for it (like "BTC")
- Smallest division (like "satoshi" - or maybe "sat"?)
- Subdivision for micropayments (like "msat")

Related: #51

**Comment by BitcoinErrorLog** [comment]
Are there any notable standards from existing token projects for this that we should model ours after?

I do not support subdivisions.

**Comment by dr-orlovsky** [comment]
None of the tokens are working on Ln, so no. Omni Bolt as far as I see uses asset definitions from onchain part and does not have LN-specific things there.

**Comment by fedsten** [comment]
Personally I don't see the point of having both "smallest division" and "subdivision for micropayments". In Bitcoin msats exists only because a technological improvement enabled further division that before was not possible, but I don't see why a brand new token shouldn't directly adopt its smallest unit also for micropayments.

**Comment by dr-orlovsky** [comment]
Follow-up from the dev call on the 7th of Oct 2020: we need just a single name, which will be used for a large aggregate unit. The atomic units will be expressed as a decimals after the dot under the same name. This works with other assets on ERC20, Liquid and other systems, and with LN we just need to make sure that the atomic unit is the unit that can be usable for micropayments (so in case of USDT it must be not a "cent", but "millicent" or something like that).

Related discussion: https://github.com/LNP-BP/LNPBPs/issues/51
