### ISSUE TITLE
RGB-21 Schema: What should be the limit of the length of the name field?

### ISSUE THREAD

**Issue by UkolovaOlga** [LNP-BP/LNPBPs#76]
According to the dev call held on the 25.11.2020 https://github.com/LNP-BP/devcalls/commit/1fbb7e77bfbc6b11bb72c8bef544e5317e447dca 

This issue is a part of discussion https://github.com/LNP-BP/LNPBPs/issues/79

**Comment by cryptoquick** [comment]
Does it make sense to impose a limit? What are the maximum limits for this? 64KB or 16MB? Are there any thresholds where there it makes sense to impose a limit, such as 255 ASCII characters, vs, say, 260?

**Comment by dr-orlovsky** [comment]
Again, the issue is heavily outdated. Sorry for occasionally bringing it back during the issue sort process.

The limits are there and they are defined with strict type system (where everything has a limits). If you believe they should be adjusted, please open a PR against current version in

https://github.com/LNP-BP/LNPBPs/blob/686158728f88be3a3737c537acdc13c5a7338a5f/lnpbp-0020.md?plain=1#L66-L69
