### ISSUE TITLE
LNPBP-4: Leak of private data in Pedersen commitment scheme

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/lnpbps#8]

**Comment by chm-diederichs** [comment]
It's not so clear what specific commitment algorithm you are proposing, but to my knowledge Pedersen commitments require two generators: `g`, `h` where `h = g.r` and r is unknown, ie `log_g(h)` , thus Pedersen commitiments are backed by DLP assumption.

Since a verifier can compute all blinding commitments, `b_i | i != k`, all `d_i | i != k` are thus known and proving `d_i = H(p_i)` is zero-knowledge would rely on the random oracle assumption.  

> Check that the sum of `P_Bx_ik + P_Dx_ik = P_Cx_ix`

It's not obvious why this equality holds. Please correct me where I'm wrong, but my understanding is as follows, the commitment `C_i` refers to:

 `C_i = d_i.g + b_i.g` .. (i)

thus, 

`C_i - C_k = (d_i - d_k).g + (b_i - b_k).g`  .. (ii) 

`C_ik = d_ik.g + b_ik.g` .. (iii)

Now it is not clear how the commitment `P_Cx_ik` is made, but since there is no mention of a blinding factor, I assume `P_Bx_ik + P_Dx_ik = P_Cx_ik` is meant to follow directly from (iii), the fact that `C_ik` is the sum of points `D_ik` and `B_ik`. However, even with a homomorphic commitment scheme, we cannot map this group property to the underlying scalar field i.e. `C = D + B =/=> C_x = D_x + B_x`. 

Could you elaborate on the commitment scheme you propose in each case and or provide a reference to proof of zero-knowledge if you've seen this scheme used elsewhere?

**Comment by chm-diederichs** [comment]
As an alternative, I would propose to stick with the canonical Pedersen commitment scheme with secret `s` and nonce (blinding factor) `t`:

`C(s, t) = s.g + t.h`

which may be revealed by providing `(s, t)`.

To prove to a verifying party that the valid nonces were provided, it is possible to make 2 commitments, `C = s.g + t.h` and `C' = s.g + t'.h`. The verifier should then check `C / C' = t - t'` to prove that both commit to the same message and `t` and `t'` are valid.

This would make the binary string `s` 1.5x longer, since two commitments are require for each message, however, this is backed by a known securtiy proof from [T. Pedersen's thesis §3.4] (https://tidsskrift.dk/daimipb/article/view/6621/5743) .

**Comment by dr-orlovsky** [comment]
Just to summarize, after dev call it was decided to stick to the alternative approach of using bloom-filer like functionality for LNPBP-3 (will be working on PR soon)

**Comment by dr-orlovsky** [comment]
The issue resulted in LNPBP-3 being updated with the new protocol
